language: python

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.6
      env: TOXENV=py26 LC_ALL=C LC_CTYPE=C
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=py27 LC_ALL=C LC_CTYPE=C
    - python: 3.3
      env: TOXENV=py33
    - python: 3.3
      env: TOXENV=py33 LC_ALL=C LC_CTYPE=C
    - python: 3.4
      env: TOXENV=py34
    - python: 3.4
      env: TOXENV=py34 LC_ALL=C LC_CTYPE=C
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=py35 LC_ALL=C LC_CTYPE=C
    - python: pypy
      env: TOXENV=pypy
    - python: pypy
      env: TOXENV=pypy LC_ALL=C LC_CTYPE=C
    - python: pypy3
      env: TOXENV=pypy3
    - python: pypy3
      env: TOXENV=pypy3 LC_ALL=C LC_CTYPE=C

script:
 - pip install tox

 # Output the env, to verify behavior
 - env

 # update egg_info based on setup.py in checkout
 - python bootstrap.py

 - tox

before_deploy:
  - export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=1
deploy:
  provider: pypi
  # Also update server in setup.cfg
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 3.5
    condition: $LC_ALL != "C"
  user: jaraco
  password:
    secure: tfWrsQMH2bHrWjqnP+08IX1WlkbW94Q30f4d7lCyhWS1FIf/jBDx4jrEILNfMxQ1NCwuBRje5sihj1Ow0BFf0vVrkaeff2IdvnNDEGFduMejaEQJL3s3QrLfpiAvUbtqwyWaHfAdGfk48PovDKTx0ZTvXZKYGXZhxGCYSlG2CE6Y6RDvnEl6Tk8e+LqUohkcSOwxrRwUoyxSnUaavdGohXxDT8MJlfWOXgr2u+KsRrriZqp3l6Fdsnk4IGvy6pXpy42L1HYQyyVu9XyJilR2JTbC6eCp5f8p26093m1Qas49+t6vYb0VLqQe12dO+Jm3v4uztSS5pPQzS7PFyjEYd2Rdb6ijsdbsy1074S4q7G9Sz+T3RsPUwYEJ07lzez8cxP64dtj5j94RL8m35A1Fb1OE8hHN+4c1yLG1gudfXbem+fUhi2eqhJrzQo5vsvDv1xS5x5GIS5ZHgKHCsWcW1Tv+dsFkrhaup3uU6VkOuc9UN+7VPsGEY7NvquGpTm8O1CnGJRzuJg6nbYRGj8ORwDpI0KmrExx6akV92P72fMC/I5TCgbSQSZn370H3Jj40gz1SM30WAli9M+wFHFd4ddMVY65yxj0NLmrP+m1tvnWdKtNh/RHuoW92d9/UFtiA5IhMf1/3djfsjBq6S9NT1uaLkVkTttqrPYJ7hOql8+g=
  distributions: release
