# Configuration for pull request documentation previews via Netlify

[build]
    publish = "docs/build/html"
    command = "pip install tox && tox -e docs --notest && ./.tox/docs/bin/pip install 'Sphinx==1.7.9' && tox -e docs"
