name: tests

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        distutils:
        - local
        python:
        - pypy-3.7
        - 3.7
        - 3.8
        - 3.9
        - "3.10"
        platform:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        include:
        - platform: ubuntu-latest
          python: "3.10"
          distutils: stdlib
    runs-on: ${{ matrix.platform }}
    env:
      SETUPTOOLS_USE_DISTUTILS: ${{ matrix.distutils }}
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox
      - name: Run tests
        run: tox -- --cov-report xml
      - name: Publish coverage
        if: false  # disabled for #2727
        uses: codecov/codecov-action@v1
        with:
          flags: >-  # Mark which lines are covered by which envs
            ${{ runner.os }},
            ${{ matrix.python }}

  test_cygwin:
    runs-on: windows-latest
    timeout-minutes: 75
    steps:
      - uses: actions/checkout@v2
      - name: Install Cygwin with Python
        uses: cygwin/cygwin-install-action@v1
        with:
          platform: x86_64
          packages: >-
            git,
            gcc-core,
            python38,
            python38-devel,
            python38-pip
      - name: Install tox
        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}
        run: |
          python3.8 -m pip install tox
      - name: Run tests
        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}
        run: |
          tox -- --cov-report xml
